[build]
command = "npm run build"
publish = "dist"

# SPA fallback sans casser les assets
[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
